# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other_core_functionalities', '0003_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other_core_functionalities.Name')),
            ],
        ),
    ]
